import sqlite3
conn = sqlite3.connect('../results.db')
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('abstract','abstrakt','abstract.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('amazing','úžasné','amazing.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('angry','nahnevaný','angry.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('autograph','podpis','autograph.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('belt','opasok','belt.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('bottom half','spodná polovica','bottom half.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('brilliant','brilantné','brilliant.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('cap','čiapka / šiltovka','cap.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('coat','kabát','coat.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('coffee','káva','coffee.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('congratulations','gratulujem','congratulations.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('drawing','kresba','drawing.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('dress','šaty','dress.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('eighty pence','osemdesiat pencí','eighty pence.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('energy','energia','energy.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('fantastic','fantastické','fantastic.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('gloves','rukavice','gloves.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('happy','šťastný','happy.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('here you are','nech sa páči','here you are.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('manager','menežér','manager.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('menu','jedálniček','menu.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('painting','maľba','painting.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('poor','chudobný','poor.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('portrait','portrét','portrait.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('realistic','realistický / verný','realistic.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('rich','bohatý','rich.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('sad','smutný','sad.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('scarf','šatka / šál','scarf.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('serious','vážny','serious.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('shirt','košela / tričko','shirt.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('shoes','topánky','shoes.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('tea','čaj','tea.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('team','tím','team.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('tights','pančušky / elasťáky','tights.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('top half','horná polovica','top half.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('tracksuit','športová súprava','tracksuit.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('trainers','tenisky','trainers.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('trousers','nohavice','trousers.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('well done','dobrá práca','well done.png')")

#one pound fifty

conn.commit()
conn.close()
