import sqlite3
conn = sqlite3.connect('../results.db')


conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("adults", "dospelí", "adults.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("adventure", "dobrodružstvo", "adventure.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("banana skin", "banánová šupka", "banana_skin.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("beach", "pláž", "beach.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("bridge", "most", "bridge.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("bus station", "autobusová stanica", "bus_station.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("car park", "parkovisko", "car_park.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("cinema", "kino", "cinema.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("Come and see", "Poď sa pozrieť", "come_and_see.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("drop", "odhodiť / kvapka", "drop.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("rubbish", "odpadky", "rubbish.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("drive", "šoférovať", "drive.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("enormous", "obrovský", "enormous.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("Excuse me", "Prepáčte", "excuse_me.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("island", "ostrov", "island.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("key", "kľúč", "key.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("lake", "jazero", "lake.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("library", "knižnica", "library.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("map", "mapa", "map.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("Me first", "Ja prvý", "me_first.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("opening times", "otváracie hodiny", "opening_times.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("park", "park", "park.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("picnic area", "pikniková oblasť", "picnic_area.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("post office", "pošta", "post_office.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("bin", "kôš", "bin.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("restaurant", "reštaurácia", "restaurant.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("river", "rieka", "river.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("school", "škola", "school.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("shop", "obchod", "shop.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("shopping centre", "nákupné centrum", "shopping_centre.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("slide", "šmykľavka", "slide.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("street", "ulica", "street.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("supermarket", "supermarket", "supermarket.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("swimming pool", "bazén", "swimming_pool.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("swing", "hojdačka", "swing.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("symbol", "symbol", "symbol.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("train station", "železničná stanica", "train_station.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("town", "mesto", "town.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("visitors", "návštevníci", "visitors.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("walk", "kráčať / prechádzka", "walk.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("wood", "drevo / les", "wood.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("chess", "šach", "chess.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("fishing", "rybačka", "fishing.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("London", "Londýn", "london.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("New York", "New York", "new_york.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("picnic", "piknik", "picnic.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("pirate ship", "pirát­ska loď", "pirate_ship.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("playground", "ihrisko", "playground.png"))

conn.commit()
conn.close()
