import sqlite3
conn = sqlite3.connect('../results.db')

conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("abdomen", "brucho", "abdomen.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("address", "adresa", "address.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("ant", "mravec", "ant.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("antennae", "tykadlá", "antennae.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("beautiful", "krásny", "beautiful.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("bee", "včela", "bee.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("boring", "nudný", "boring.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("butterfly", "motýľ", "butterfly.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("canary", "kanárik", "canary.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("chameleon", "chameleón", "chameleon.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("colour", "farba", "colour.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("crawl", "plaziť sa", "crawl.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("dragonfly", "vážka", "dragonfly.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("field", "pole", "field.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("fish", "ryba", "fish.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("fly", "mucha", "fly.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("fun", "zábava", "fun.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("grass", "tráva", "grass.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("grasshopper", "koník", "grasshopper.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("guinea pig", "morské prasiatko", "guinea_pig.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("head", "hlava", "head.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("jungle", "džungľa", "jungle.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("ladybird", "lienka", "ladybird.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("lay eggs", "klásť vajíčka", "lay_eggs.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("legs", "nohy", "legs.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("lizard", "jašterica", "lizard.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("mountain", "hora", "mountain.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("owner", "majiteľ", "owner.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("parrot", "papagáj", "parrot.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("python", "pytón", "python.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("queen bee", "včelia kráľovná", "queen_bee.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("rabbit", "králik", "rabbit.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("reptile", "plaz", "reptile.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("sea", "more", "sea.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("shame", "hanba", "shame.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("snail", "slimák", "snail.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("snake", "had", "snake.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("spider", "pavúk", "spider.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("stamp", "poštová známka", "stamp.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("stick insect", "paličkový hmyz", "stick_insect.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("sting", "žihadlo", "sting.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("stripy", "pruhovaný", "stripy.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("teeth", "zuby", "teeth.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("thorax", "hruď", "thorax.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("Too bad!", "Škoda!", "too_bad.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("tortoise", "korytnačka", "tortoise.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("wings", "krídla", "wings.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("world", "svet", "world.png"))

conn.commit()
conn.close()
