import sqlite3
conn = sqlite3.connect('../results.db')

conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("asparagus", "špargľa", "asparagus.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("birthday", "narodeniny", "birthday.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("biscuits", "sušienky", "biscuits.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("bowl", "miska", "bowl.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("breakfast", "raňajky", "breakfast.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("broccoli", "brokolica", "broccoli.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("butter", "maslo", "butter.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("cake", "koláč", "cake.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("cheese", "syr", "cheese.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("chop", "sekať", "chop.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("chocolate", "čokoláda", "chocolate.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("cocoa", "kakao", "cocoa.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("cocoa beans", "kakaové bôby", "cocoa_beans.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("coconut", "kokos", "coconut.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("delicious", "chutný", "delicious.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("eggs", "vajcia", "eggs.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("flour", "múka", "flour.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("flower", "kvet", "flower.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("fork", "vidlička", "fork.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("fruit", "ovocie", "fruit.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("leaf", "list", "leaf.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("Let’s buy", "Poďme kúpiť", "Lets_buy.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("Look out", "Pozor", "Look_out.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("maize", "kukurica", "maize.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("mayonnaise", "majonéza", "mayonnaise.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("melon", "melón", "melon.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("mouse", "myš", "mouse.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("mice", "myši", "mice.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("Off you go", "Len choď", "Off_you_go.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("paper", "papier", "paper.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("pasta", "cestoviny", "pasta.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("pizza", "pizza", "pizza.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("plate", "tanier", "plate.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("present", "darček", "present.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("Ready steady go", "Pripraviť sa pozor štart", "Ready_steady_go.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("recipe", "recept", "recipe.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("root", "koreň", "root.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("rubber", "guma", "rubber.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("ruler", "pravítko", "ruler.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("salad", "šalát", "salad.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("sauce", "omáčka", "sauce.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("scissors", "nožnice", "scissors.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("seed", "semienko", "seed.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("shake", "triasť", "shake.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("soup", "polievka", "soup.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("spinach", "špenát", "spinach.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("stem", "stonka", "stem.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("stop", "zastaviť", "stop.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("strawberries", "jahody", "strawberries.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("sugar", "cukor", "sugar.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("tea leaves", "čajové lístky", "tea_leaves.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("teatime", "čas na čaj", "teatime.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("top", "vrch", "top.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("tray", "podnos", "tray.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("vanilla", "vanilka", "vanilla.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("What are you doing", "Čo robíš", "What_are_you_doing.png"))

conn.commit()
conn.close()
