import sqlite3
conn = sqlite3.connect('results.db')
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('afternoon','poobedie','afternoon.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('at school','v škole','at school.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('bag','taška','bag.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('bed','posteľ','bed.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('big hand','veľká ručička','big hand.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('blade','čepeľ','blade.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('bus','autobus','bus.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('cards','karty','cards.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('carry','nosiť','carry.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('cat','mačka','cat.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('clock','hodiny','clock.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('club','klub','club.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('clubhouse','klubovňa','clubhouse.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('digital clock','digitálne hodiny','digital clock.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('drink','piť / nápoj','drink.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('evening','večer','evening.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('everyone','všetci','everyone.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('face','tvár','face.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('football','futbalka','football.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('frog','žaba','frog.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('glasses','okuliare','glasses.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('go away','choď preč','go away.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('have fun','bav sa','have fun.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('hour','hodina','hour.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('join','spojiť','join.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('magazine','časopis','magazine.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('member','člen','member.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('mess','neporiadok','mess.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('minute','minúta','minute.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('morning','ráno','morning.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('night','noc','night.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('outing','vychádzka','outing.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('place','miesto','place.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('poor cat','chúďa mačka','poor cat.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('rollerblades','korčule','rollerblades.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('second','sekunda','second.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('sleep','spánok','sleep.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('small hand','malá ručička','small hand.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('sweets','sladkosti','sweets.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('trip','výlet','trip.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('umbrella','dáždnik','umbrella.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('watch','hodinky','watch.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('wear','obliekať / oblečenie','wear.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('welcome','vitaj','welcome.png')")

conn.commit()
conn.close()



