import sqlite3
conn = sqlite3.connect('../results.db')

conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('band','skupina','band.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('bear','medveď','bear.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('blanket','deka','blanket.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('book','kniha','book.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('certificate','certifikát','certificate.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('check it','skontroluj to','check it.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('comb','hrebeň','comb.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('competition','súťaž','competition.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('costume','kostým','costume.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('dark','temnota','dark.png')")
#conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('don\'t forget','nezabudni','dont forget.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("don't forget", "nezabudni", "dont forget.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('drum','bubon','drum.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('everything','všetko','everything.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('fast','rýchlo','fast.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('festival','festival','festival.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('high','vysoko','high.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('hook','hák','hook.png')")
#conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('I can\'t find','neviem nájsť','I cant find.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES (?, ?, ?)", ("I can't find", "neviem nájsť" , "I cant find.png"))
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('instrument','nástroj','instrument.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('it sounds like','to znie ako','it sounds like.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('japan','japonsko','Japoan.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('look','pozri','look.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('loud','nahlas','loud.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('low','nízko','low.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('mat','rohož','mat.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('owl','sova','owl.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('pillow','vankúš','pillow.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('postcard','pohľadnica','postcard.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('pyjamas','pyžamo','pyjamas.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('quiet','ticho','quiet.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('ready','pripravený','ready.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('scared','vystrašený','scared.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('sleeping bag','spacák','sleeping bag.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('slow','pomaly','slow.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('spotty','fľakatý','spotty.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('strings','struny','strings.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('sunglasses','slnečné okuliare','sunglasses.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('teddy','medvedík','teddy.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('tidy','uprataný','tidy.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('toothbrush','zubná kefka','toothbrush.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('torch','fakľa','torch.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('towel','uterák','towel.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('traditional','tradičný','traditional.png')")
conn.execute("INSERT INTO vocabulary (english, slovak, image) VALUES ('tunic','tunika','tunic.png')")

conn.commit()
conn.close()
